### ISSUE TITLE
TypeInferenceAnalysis crashes with multidimensional array

### ISSUE THREAD

**Issue by m-carrasco** [edgardozoppi/analysis-net#4]
The following code makes analysis-net crash when using TypeInferenceAnalysis.

```
static void arrayTest8()
{
    var a = new int[510, 10];
    a[1, 0] = 1 ;
}
```

Best regards,
Manuel

**Comment by edgardozoppi** [comment]
Thanks a lot for reporting the bug! It should be fixed now.
